name: incubapp_lite
description: A new Flutter project.

# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^2.12.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  font_awesome_flutter: ^10.5.0
  google_fonts: ^5.1.0
  android_flutter_wifi: ^0.1.2
  connectivity: ^3.0.6
  permission_handler: ^9.2.0
  firebase_auth: ^3.3.3
  firebase_core: ^1.10.6
  webview_flutter: ^2.0.13



dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^2.0.0



flutter:

  assets:
    - assets/logo.png

  uses-material-design: true

